=== endeavourhealth/Enterprise/src/enterprise-core/src/main/resources/EntityMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="entityMap" type="entityMap"/>
	<xs:complexType name="entityMap">
		<xs:sequence>
			<xs:element name="entity" type="entity" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="entity">
		<xs:sequence>
			<xs:element name="logicalName" type="xs:string"/>
			<xs:element name="displayName" type="xs:string"/>
			<xs:element name="resultSetIndex" type="xs:int"/>
			<xs:element name="cardinality" type="cardinality"/>
			<xs:element name="populationFieldIndex" type="xs:int"/>
			<xs:element name="organisationOdsFieldIndex" type="xs:int" minOccurs="0"/>
			<xs:element name="field" type="field" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="field">
		<xs:sequence>
			<xs:element name="logicalName" type="xs:string"/>
			<xs:element name="displayName" type="xs:string"/>
			<xs:element name="index" type="xs:int"/>
			<xs:element name="availability" type="availabilities"/>
			<xs:element name="logicalDataType" type="logicalDataType"/>			
			<xs:element name="dataValues" type="dataValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="logicalDataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="datetime"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="uuid"/>
			<xs:enumeration value="code"/>
			<xs:enumeration value="dataValues"/>
			<xs:enumeration value="organisationODS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="cardinality">
		<xs:restriction base="xs:string">
			<xs:enumeration value="single"/>
			<xs:enumeration value="multiple"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="availabilities">
		<xs:list>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="search"/>
					<xs:enumeration value="output"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:list>
	</xs:simpleType>
	<xs:complexType name="dataValueType">
		<xs:sequence>
			<xs:element name="logicalValue" type="xs:string"/>
			<xs:element name="physicalValue" type="xs:string"/>
			<xs:element name="displayName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== endeavourhealth/Enterprise/src/enterprise-core/src/main/resources/EntityMap.xml
<entityMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityMap.xsd">
	<entity>
		<logicalName>PATIENT</logicalName>
		<displayName>Patient</displayName>
		<resultSetIndex>1</resultSetIndex>
		<cardinality>single</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>PSEUDO_ID</logicalName>
			<displayName>Pseudo Identifier</displayName>
			<index>3</index>
			<availability>output</availability>
			<logicalDataType>string</logicalDataType>
		</field>
		<!--
		<organisationOdsFieldIndex>2</organisationOdsFieldIndex>
		<field>
			<logicalName>ORGANISATION_ODS</logicalName>
			<displayName>Organisation ODS Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>organisationODS</logicalDataType>
		</field>
		-->
		<field>
			<logicalName>DOB</logicalName>
			<displayName>Date Of Birth</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Age-->
		<field>
			<logicalName>GENDER</logicalName>
			<displayName>Gender</displayName>
			<index>5</index>
			<availability>search output</availability>
			<logicalDataType>dataValues</logicalDataType>
			<dataValues>
				<logicalValue>MALE</logicalValue>
				<physicalValue>0</physicalValue>
				<displayName>Male</displayName>
			</dataValues>
			<dataValues>
				<logicalValue>FEMALE</logicalValue>
				<physicalValue>1</physicalValue>
				<displayName>Female</displayName>
			</dataValues>
			<dataValues>
				<logicalValue>OTHER</logicalValue>
				<physicalValue>2</physicalValue>
				<displayName>Other</displayName>
			</dataValues>
			<dataValues>
				<logicalValue>UNKNOWN</logicalValue>
				<physicalValue>3</physicalValue>
				<displayName>Unknown</displayName>
			</dataValues>
		</field>
		<field>
			<logicalName>REGISTRATION_DATE</logicalName>
			<displayName>Registration Date</displayName>
			<index>6</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<field>
			<logicalName>REGISTRATION_END_DATE</logicalName>
			<displayName>Registration End Date</displayName>
			<index>6</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!-- Registration type -->
		<!-- Usual GP-->
		<field>
			<logicalName>YEAR_OF_DEATH</logicalName>
			<displayName>Year of Death</displayName>
			<index>6</index>
			<availability>search output</availability>
			<logicalDataType>integer</logicalDataType>
		</field>
	</entity>
	<entity>
		<logicalName>ALLERGY_INTOLERANCE</logicalName>
		<displayName>Allergy/Intolerance</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>CONDITION</logicalName>
		<displayName>Condition</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Is Review (boolean or lookup?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>DIAGNOSTIC_ORDER</logicalName>
		<displayName>Diagnostic Order</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>DIAGNOSTIC_REPORT</logicalName>
		<displayName>Diagnostic Report</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>FAMILY_MEMBER_HISTORY</logicalName>
		<displayName>Family Member History</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>IMMUNISATION</logicalName>
		<displayName>Immunisation</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>MEDICATION_ORDER</logicalName>
		<displayName>Medication Order</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
			<!--Needs to be DM&D code-->
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<field>
			<logicalName>ESTIMATED_COST</logicalName>
			<displayName>Estimated Cost</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>float</logicalDataType>
		</field>
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>OBSERVATION</logicalName>
		<displayName>Observation</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<field>
			<logicalName>VALUE</logicalName>
			<displayName>Value</displayName>
			<index>4</index>
			<availability>search output</availability>
			<logicalDataType>float</logicalDataType>
		</field>
		<field>
			<logicalName>UNITS</logicalName>
			<displayName>Units</displayName>
			<index>4</index>
			<availability>output</availability>
			<logicalDataType>string</logicalDataType>
		</field>
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>PROCEDURE</logicalName>
		<displayName>Procedure</displayName>
		<resultSetIndex>2</resultSetIndex>
		<cardinality>multiple</cardinality>
		<populationFieldIndex>1</populationFieldIndex>
		<field>
			<logicalName>CODE</logicalName>
			<displayName>Code</displayName>
			<index>2</index>
			<availability>search output</availability>
			<logicalDataType>code</logicalDataType>
		</field>
		<!--Code Term-->
		<field>
			<logicalName>EFFECTIVE_DATE</logicalName>
			<displayName>Clinical Effective Date</displayName>
			<index>3</index>
			<availability>search output</availability>
			<logicalDataType>date</logicalDataType>
		</field>
		<!--Date precision?-->
		<!--Practitioner-->
	</entity>
	<entity>
		<logicalName>PROCEDURE_REQUEST</logicalName>
		<displayName>Procedure Request</displayName>
		<resultSetIndex>2</resultSetIndex>
